print("Hello.")
print(" Welcome to my MadLib!")
print (" Let's get started!")
print ("Adjective")
Adjective = input ()
print ("Adjective2")
Adjective2 = input ()
print ("Pluralnoun")
Pluralnoun = input ()
print("Adjective3")
Adjective3 = input ()
print ("Noun2")
Noun2 = input ()
print ("PluralNoun2")
Pluralnoun2 = input ()
print ("Adjective4")
Adjective4 = input ()
print (" One the first day of school, I felt " + Adjective + ".")
print (" I put on my favorite new outfit- a shirt with two " +  Adjective2+ " " +  Pluralnoun + " on it.")
print (" I also had a " + Adjective3 + " pair of " + Noun2+ " pants.")
print (" My mom made me my favorite breakfast," +  Pluralnoun2 + " and pancakes.")
print (" My teacher told me my new teacher was really " + Adjective4 + " in class.")

